// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

#import "GPBProtocolBuffers_RuntimeSupport.h"
#import "Person.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma mark - PersonRoot

@implementation PersonRoot

@end

static GPBFileDescriptor *PersonRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - PBUser

@implementation PBUser

@dynamic hasUserId, userId;
@dynamic hasNick, nick;
@dynamic hasAvatar, avatar;

typedef struct PBUser_Storage {
  uint32_t _has_storage_[1];
  NSString *userId;
  NSString *nick;
  NSString *avatar;
} PBUser_Storage;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = NULL;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "userId",
        .number = PBUser_FieldNumber_UserId,
        .hasIndex = 0,
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .type = GPBTypeString,
        .offset = offsetof(PBUser_Storage, userId),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "nick",
        .number = PBUser_FieldNumber_Nick,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBUser_Storage, nick),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "avatar",
        .number = PBUser_FieldNumber_Avatar,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .type = GPBTypeString,
        .offset = offsetof(PBUser_Storage, avatar),
        .defaultValue.valueString = nil,
        .typeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
#if GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    const char *extraTextFormatInfo = NULL;
#else
    static const char *extraTextFormatInfo = "\001\001\006\000";
#endif  // GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    descriptor = [GPBDescriptor allocDescriptorForClass:[PBUser class]
                                              rootClass:[PersonRoot class]
                                                   file:PersonRoot_FileDescriptor()
                                                 fields:fields
                                             fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                                 oneofs:NULL
                                             oneofCount:0
                                                  enums:NULL
                                              enumCount:0
                                                 ranges:NULL
                                             rangeCount:0
                                            storageSize:sizeof(PBUser_Storage)
                                             wireFormat:NO
                                    extraTextFormatInfo:extraTextFormatInfo];
  }
  return descriptor;
}

@end


// @@protoc_insertion_point(global_scope)
