// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class PBUser;
@class PBUserBuilder;



@interface PersonRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define PBUser_userId @"userId"
#define PBUser_nick @"nick"
#define PBUser_avatar @"avatar"
@interface PBUser : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUserId_:1;
  BOOL hasNick_:1;
  BOOL hasAvatar_:1;
  NSString* userId;
  NSString* nick;
  NSString* avatar;
}
- (BOOL) hasUserId;
- (BOOL) hasNick;
- (BOOL) hasAvatar;
@property (readonly, strong) NSString* userId;
@property (readonly, strong) NSString* nick;
@property (readonly, strong) NSString* avatar;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PBUserBuilder*) builder;
+ (PBUserBuilder*) builder;
+ (PBUserBuilder*) builderWithPrototype:(PBUser*) prototype;
- (PBUserBuilder*) toBuilder;

+ (PBUser*) parseFromData:(NSData*) data;
+ (PBUser*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBUser*) parseFromInputStream:(NSInputStream*) input;
+ (PBUser*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PBUser*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PBUser*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PBUserBuilder : PBGeneratedMessageBuilder {
@private
  PBUser* resultPbuser;
}

- (PBUser*) defaultInstance;

- (PBUserBuilder*) clear;
- (PBUserBuilder*) clone;

- (PBUser*) build;
- (PBUser*) buildPartial;

- (PBUserBuilder*) mergeFrom:(PBUser*) other;
- (PBUserBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PBUserBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (NSString*) userId;
- (PBUserBuilder*) setUserId:(NSString*) value;
- (PBUserBuilder*) clearUserId;

- (BOOL) hasNick;
- (NSString*) nick;
- (PBUserBuilder*) setNick:(NSString*) value;
- (PBUserBuilder*) clearNick;

- (BOOL) hasAvatar;
- (NSString*) avatar;
- (PBUserBuilder*) setAvatar:(NSString*) value;
- (PBUserBuilder*) clearAvatar;
@end


// @@protoc_insertion_point(global_scope)
